{% set name = "sqlacodegen" %}
{% set version = "2.2.0" %}
{% set sha256 = "83e7ae401398cc1ae8324722a3294d7faadb694347cb7e2c0fb8c15a3f1eb515" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - sqlacodegen = sqlacodegen.main:main

requirements:
  host:
    - python
    - pip
    - setuptools  >=36.2.7
    - setuptools_scm  >=1.7.0

  run:
    - python
    - sqlalchemy >=0.9.0
    - inflect >=0.2.0

test:
  imports:
    - sqlacodegen

about:
  home: http://pypi.python.org/pypi/sqlacodegen/
  license: MIT
  license_file: LICENSE
  summary: Automatic model code generator for SQLAlchemy
  license_family: MIT

extra:
  recipe-maintainers:
    - rzillman
    - dhirschfeld
