travis:
  secure:
    BINSTAR_TOKEN: ZfAs704lksZq4iuUNvYilOxdKAuzyctTwxIgWyCudAreXMGbZvpctG9STnE1p8tKppqlRAmHj8HoqqqbwZdnDGwAc2hz7RtlskKY3RKmsAH3Rrju31g8NVecIQBhJsC5g/RsClMofS/coCWQgkskw4trMPK6gCee14yXv4sULMv+nWfwxlHp9EwjXx7BVJUoyFhlt+K4yML3XpY6F3+gmGT1kgv0zCBs4cd4msBQF1CIeE6OMXhXmQeXOuS4A0Nty8vDsuGveHS4+8q+SbF7TyYA+aE+MvLybFkIg8F1ysOUWlIy1tSXlwRTylVFLt6YJuw/09srhb/7R2tV0ZIfNEr7HPo8yUeXdcnf+XIIK6c2Haj/EZXhHTrFAIq/WNboLW2q0txvb95+aPafY+1A7vdAWrYQdJDrILJTeFN2eeoP2G5Dcc6wmd4Nh/8QO+uZ7dqBu7B7FQV4vLNB3kBXcgFVN17qbkOnRajWFcz/miDg57BTgcgJSjgNBUj0qi2uGQsjpU/FRuXTV7Z/HMdMRoYvMtWBwQmFXGGrYcXrGCd4KWccoLXZrLd8gX8LyQmevPnMewMHFQxtMvPuhLhuZroXvjKUauqxH8EwbFVdulX70wiHa+iIqSRgElFatT7XCN7wSDyfs5oktWxax6Dhhn1SL5NbLV4kxO32Wm7yhFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
