travis:
  secure:
    BINSTAR_TOKEN: QpFWcnXLNoDwBrksPbNRjFweWGIIa0Mfx192d446EEL0nKSF78V/snrEIQ+CMdXQ/cOMcdXXqYNPl6mzKdHul8Nx3kVx/QWAGab9/+1rGAt/S1hxhEwWxrK6g0PticILTJZI2H69nBhJwLqMnElxvSwLU4eEoIYK0/GaEJth9EQD99Y0WCzzCHNXPJ1PD/ENxk6xMCG/HbhTeBLGfvxFdgGoFmH78bRcJ3cpLZShfBuAlZ+Fdz5iG0QnEp9OarSMwLILLEUjYQEm/1WsSSGcMkF1Sq/ERzA4PGM3rc/eJlwONT930pSZ5xnJLuC1SZmbwhKiCiJtvu12ZVYRGGfA/U8TteIFLpjaafHEP05ZHDjTsx0rMLSGLRs6OLWFHt0MKV4H1mjN1k7wsCqJgWVZ90Ji3hr5Ns4z5cfC5Vf4KG3fSFbBzi6zb+Tjx9KxbOSai2/RlMDKHDD2GyOq7g2C4FFt3ECqofX9LqOG3hcwja6U7rNASObGIUJXEGs5pFei/nWIG1RD+w8w/on0hbuWalDuZnBeWf/6x/aGRXO3dSZQxvs0XR3owaOwA6S9irasMsp+I3N6l26iLV1Us9RtKz6oMgXLFUJ3yLk8Eb/rB91olotrdsgEC9LF/k4+smxrKN7ILdXF7yNg/wsdIcZR2fZ2Yt4S/6sYyrpIbPdtaHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
